/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as FundadorRouteImport } from './routes/fundador'
import { Route as FloreriasRouteImport } from './routes/florerias'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProyectosIdRouteImport } from './routes/proyectos.$id'
import { Route as BlogPorQueMiPaginaWebNoVendeRouteImport } from './routes/blog.por-que-mi-pagina-web-no-vende'

const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const FundadorRoute = FundadorRouteImport.update({
  id: '/fundador',
  path: '/fundador',
  getParentRoute: () => rootRouteImport,
} as any)
const FloreriasRoute = FloreriasRouteImport.update({
  id: '/florerias',
  path: '/florerias',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyectosRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ProyectosIdRoute = ProyectosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProyectosRoute,
} as any)
const BlogPorQueMiPaginaWebNoVendeRoute =
  BlogPorQueMiPaginaWebNoVendeRouteImport.update({
    id: '/por-que-mi-pagina-web-no-vende',
    path: '/por-que-mi-pagina-web-no-vende',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/florerias': typeof FloreriasRoute
  '/fundador': typeof FundadorRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/blog/por-que-mi-pagina-web-no-vende': typeof BlogPorQueMiPaginaWebNoVendeRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/blog/': typeof BlogIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/florerias': typeof FloreriasRoute
  '/fundador': typeof FundadorRoute
  '/blog/por-que-mi-pagina-web-no-vende': typeof BlogPorQueMiPaginaWebNoVendeRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/blog': typeof BlogIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/florerias': typeof FloreriasRoute
  '/fundador': typeof FundadorRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/blog/por-que-mi-pagina-web-no-vende': typeof BlogPorQueMiPaginaWebNoVendeRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/blog/': typeof BlogIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contacto'
    | '/diagnostico'
    | '/florerias'
    | '/fundador'
    | '/proyectos'
    | '/blog/por-que-mi-pagina-web-no-vende'
    | '/proyectos/$id'
    | '/blog/'
    | '/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/diagnostico'
    | '/florerias'
    | '/fundador'
    | '/blog/por-que-mi-pagina-web-no-vende'
    | '/proyectos/$id'
    | '/blog'
    | '/proyectos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contacto'
    | '/diagnostico'
    | '/florerias'
    | '/fundador'
    | '/proyectos'
    | '/blog/por-que-mi-pagina-web-no-vende'
    | '/proyectos/$id'
    | '/blog/'
    | '/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  FloreriasRoute: typeof FloreriasRoute
  FundadorRoute: typeof FundadorRoute
  ProyectosRoute: typeof ProyectosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundador': {
      id: '/fundador'
      path: '/fundador'
      fullPath: '/fundador'
      preLoaderRoute: typeof FundadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florerias': {
      id: '/florerias'
      path: '/florerias'
      fullPath: '/florerias'
      preLoaderRoute: typeof FloreriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/proyectos/$id': {
      id: '/proyectos/$id'
      path: '/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof ProyectosIdRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/blog/por-que-mi-pagina-web-no-vende': {
      id: '/blog/por-que-mi-pagina-web-no-vende'
      path: '/por-que-mi-pagina-web-no-vende'
      fullPath: '/blog/por-que-mi-pagina-web-no-vende'
      preLoaderRoute: typeof BlogPorQueMiPaginaWebNoVendeRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogPorQueMiPaginaWebNoVendeRoute: typeof BlogPorQueMiPaginaWebNoVendeRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPorQueMiPaginaWebNoVendeRoute: BlogPorQueMiPaginaWebNoVendeRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProyectosRouteChildren {
  ProyectosIdRoute: typeof ProyectosIdRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

const ProyectosRouteChildren: ProyectosRouteChildren = {
  ProyectosIdRoute: ProyectosIdRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}

const ProyectosRouteWithChildren = ProyectosRoute._addFileChildren(
  ProyectosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  FloreriasRoute: FloreriasRoute,
  FundadorRoute: FundadorRoute,
  ProyectosRoute: ProyectosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
